import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

test('public SEO URLs use the final www production host', () => {
  const sitemap = read('public/sitemap.xml');
  const robots = read('public/robots.txt');
  const seo = read('src/components/Seo.jsx');
  const prerender = read('scripts/prerender-public-routes.mjs');
  const index = read('index.html');
  const envExample = read('.env.example');
  const checkout = read('supabase/functions/create-checkout-session/index.ts');
  const portal = read('supabase/functions/create-portal-session/index.ts');
  const vercel = read('vercel.json');
  const manifest = read('src/routeManifest.js');

  assert.match(robots, /Sitemap:\s+https:\/\/www\.resumeats\.cv\/sitemap\.xml/);
  assert.doesNotMatch(robots, /Sitemap:\s+https:\/\/resumeats\.cv\//);
  assert.match(sitemap, /<loc>https:\/\/www\.resumeats\.cv\//);
  assert.doesNotMatch(sitemap, /<loc>https:\/\/resumeats\.cv\//);
  assert.match(seo, /import\.meta\.env\.VITE_SITE_URL \|\| 'https:\/\/www\.resumeats\.cv'/);
  assert.match(seo, /if \(isIndexablePublicPage\) \{/);
  assert.match(seo, /setMetaContent\('meta\[property="og:url"\]', \{ property: 'og:url' \}, canonicalUrl\)/);
  assert.match(seo, /document\.head\.querySelector\('meta\[property="og:url"\]'\)\?\.remove\(\)/);
  assert.match(seo, /document\.head\.querySelector\('link\[rel="canonical"\]'\)\?\.remove\(\)/);
  assert.match(seo, /setStructuredData\(null\)/);
  assert.match(index, /canonical" href="https:\/\/www\.resumeats\.cv\//);
  assert.match(index, /property="og:url" content="https:\/\/www\.resumeats\.cv\//);
  assert.match(index, /property="og:image" content="https:\/\/www\.resumeats\.cv\//);
  assert.match(index, /name="twitter:image" content="https:\/\/www\.resumeats\.cv\//);
  assert.match(prerender, /process\.env\.VITE_SITE_URL \|\| 'https:\/\/www\.resumeats\.cv'/);
  assert.match(prerender, /route-manifest\.mjs/);
  assert.match(prerender, /route\.indexable === false \? 'noindex,follow' : 'index,follow'/);
  assert.match(manifest, /\['\/return-from-stripe'/);
  assert.match(manifest, /\['\/return-from-paypal'/);
  assert.match(manifest, /canonical:\s*false/);
  assert.match(prerender, /const notFoundRoute = \{/);
  assert.match(prerender, /path\.join\(distDir, '404\.html'\)/);
  assert.match(seo, /const notFoundMetadata = \{/);
  assert.match(seo, /title: 'Page Not Found - ResumeATS'/);
  assert.match(seo, /description: 'The ResumeATS page you requested could not be found\.'/);
  assert.match(seo, /\|\| notFoundMetadata/);
  assert.match(vercel, /return-from-stripe\|return-from-paypal/);
  assert.match(vercel, /"source": "\/builder\/:resumeId"/);
  assert.match(vercel, /"source": "\/preview\/:resumeId"/);
  assert.match(vercel, /"framework": null/);
  assert.doesNotMatch(vercel, /"destination": "\/builder\/index\.html"/);
  assert.doesNotMatch(vercel, /"destination": "\/preview\/index\.html"/);
  assert.doesNotMatch(vercel, /"destination": "\/return-from-stripe\/index\.html"/);
  assert.match(manifest, /\['\/preview', 'Resume Preview - ResumeATS'/);
  assert.doesNotMatch(vercel, /"source": "\/\(\.\*\)"[\s\S]*?"destination": "\/"/);
  assert.match(envExample, /SITE_URL=https:\/\/www\.resumeats\.cv/);
  assert.match(envExample, /VITE_APP_URL=https:\/\/www\.resumeats\.cv/);
  assert.match(envExample, /VITE_STRIPE_SUCCESS_URL=https:\/\/www\.resumeats\.cv\/subscription\/success/);
  assert.match(envExample, /VITE_STRIPE_CANCEL_URL=https:\/\/www\.resumeats\.cv\/pricing/);
  assert.match(checkout, /Deno\.env\.get\('SITE_URL'\) \|\| 'https:\/\/www\.resumeats\.cv'/);
  assert.match(checkout, /const success_url_for_stripe = `\$\{baseUrl\}\/return-from-stripe/);
  assert.match(checkout, /const cancel_url_for_stripe = `\$\{baseUrl\}\$\{actualCancelPath/);
  assert.match(portal, /Deno\.env\.get\("SITE_URL"\) \|\| "https:\/\/www\.resumeats\.cv"/);
  assert.match(portal, /let safeReturnUrl = `\$\{defaultReturnOrigin\}\/dashboard`/);
  assert.doesNotMatch(seo, /recruiter-approved templates/i);
  assert.doesNotMatch(prerender, /recruiter-approved templates/i);
});
