/**
 * Utility functions for handling certifications in resume generation
 *
 * This version has been updated to remove all preset certification data
 * to ensure all certifications are 100% generated by AI.
 */

/**
 * This function has been modified to no longer return preset certifications.
 * All certifications should now be generated by AI.
 *
 * @param {string} jobCategory - The job category (from jobTitleExtractor.js)
 * @returns {Object} - Empty object as we no longer use preset certifications
 */
export function getCertificationsForJobCategory(_jobCategory) { // jobCategory was unused
  // Return an empty object with empty certifications array
  // This ensures no preset data is used
  return {
    certifications: [],
    description: "All certifications are now generated by AI based on the job description"
  };
}

/**
 * This function has been modified to no longer return preset certifications.
 * All certifications should now be generated by AI.
 *
 * @param {string} jobCategory - The job category
 * @returns {Object} - Empty certification object
 */
export function getRandomCertificationForJobCategory(_jobCategory) { // jobCategory was unused
  // Return an empty certification object
  // This ensures no preset data is usedd
  return {
    name: "",
    issuer: ""
  };
}

/**
 * Always returns true for any certification, as we now rely on AI to generate appropriate certifications
 * @param {Object} certification - The certification object with name and issuer
 * @param {string} jobCategory - The job category
 * @returns {boolean} - Always returns true as we trust AI-generated certifications
 */
export function validateCertificationForJobCategory(certification, _jobCategory) { // jobCategory was unused
  // Simply check if the certification has a name
  return certification && certification.name && certification.name.trim() !== '';
}

/**
 * No longer replaces certifications with preset data
 * Only ensures the certification objects have the required structure
 * @param {Array} certifications - Array of certification objects
 * @param {string} jobCategory - The job category
 * @returns {Array} - Array of certification objects with proper structure
 */
export function fixCertificationsForJobCategory(certifications, _jobCategory) { // jobCategory was unused
  if (!certifications || !Array.isArray(certifications)) return [];

  // Just ensure each certification has the required fields
  return certifications.map(cert => ({
    name: cert.name || '',
    issuer: cert.issuer || '',
    date: cert.date || '',
    description: cert.description || ''
  }));
}
